version: "3.7"
services:
  bot:
    build:
      context: .
      dockerfile: ./Dockerfile
    tty: true
    env_file:
      - .env

    restart: unless-stopped

  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - 6379:6379
    command: redis-server --save 20 1
    volumes:
      - cache:/data